server:
  port: 8080
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.63.131:3306/dongbao-mall-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:com.sjzd.dongbao.mappper.*Mapper.xml
  type-aliases-package: com.sjzd.dongbao.entity